name: Code Quality Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black isort flake8 pylint
          python -m pip install -r ClientAdvisor/App/requirements-dev.txt
          python -m pip install -r ResearchAssistant/App/requirements-dev.txt

      - name: Format with isort
        run: |
          echo "Running isort for the entire project..."
          python -m isort . --profile=black

      - name: Format with Black
        run: |
          echo "Running Black for the entire project..."
          python -m black .

      - name: Run Flake8
        run: |
          echo "Running Flake8 for Client Advisor..."
          python -m flake8 --config=ClientAdvisor/App/.flake8 ClientAdvisor/App --verbose
          echo "Running Flake8 for Research Assistant..."
          python -m flake8 --config=ResearchAssistant/App/.flake8 ResearchAssistant/App --verbose

      - name: Run Pylint
        run: |
          echo "Running Pylint for the entire project..."
          python -m pylint . --rcfile=.pylintrc